DROP DATABASE IF EXISTS `UNIV`;

CREATE DATABASE `UNIV`;

USE `UNIV`;

DROP TABLE IF EXISTS `STUDENT`;

CREATE TABLE `STUDENT` (
	`STD_NUM`	VARCHAR(10) PRIMARY KEY	NOT NULL,
	`STD_MJ_NUM`	CHAR(3)	NOT NULL,
	`STD_SD_NUM`	INT	NOT NULL
);

DROP TABLE IF EXISTS `RATIO`;

CREATE TABLE `RATIO` (
	`RAT_NUM`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`RAT_MID`	INT DEFAULT 35	NULL,
	`RAT_FIN`	INT DEFAULT 45	NULL,
	`RAT_HW`	INT DEFAULT 10	NULL,
	`RAT_ATT`	INT DEFAULT 10	NULL
);

DROP TABLE IF EXISTS `GRADE`;

CREATE TABLE `GRADE` (
	`GR_NUM`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`GR_STD_NUM`	VARCHAR(10)	NOT NULL,
	`GR_LEC_NUM`	INT	NOT NULL,
	`GR_MIDDLE`	INT	NULL,
	`GR_FINAL`	INT	NULL,
	`GR_HOMEWORK`	INT	NULL,
	`GR_ATT`	INT	NULL,
	`GR_GRADE`	VARCHAR(2)	NULL
);

DROP TABLE IF EXISTS `STUDENT_APPLICATION`;

CREATE TABLE `STUDENT_APPLICATION` (
	`SA_NUM`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`SA_NAME`	VARCHAR(20)	NULL,
	`SA_PHONE`	VARCHAR(20)	NULL,
	`SA_RESIDENT`	CHAR(14)	NULL
);

DROP TABLE IF EXISTS `PROFESSOR`;

CREATE TABLE `PROFESSOR` (
	`PRF_NUM`	CHAR(8) PRIMARY KEY	NOT NULL,
	`PRF_MJ_NUM`	CHAR(3)	NOT NULL,
	`PRF_NAME`	VARCHAR(20) NOT	NULL,
	`PRF_PHONE`	VARCHAR(20)	NULL,
	`PRF_RESIDENT`	CHAR(14) NOT	NULL,
	`PRF_POSITION`	ENUM("HEAD","N") DEFAULT "N"	NULL
);

DROP TABLE IF EXISTS `STUDENT_DATA`;

CREATE TABLE `STUDENT_DATA` (
	`SD_NUM`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`SD_NAME`	VARCHAR(20)	NULL,
	`SD_PHONE`	VARCHAR(20)	NULL,
	`SD_RESIDENT`	CHAR(14)	NULL
);

DROP TABLE IF EXISTS `TIMETABLE`;

CREATE TABLE `TIMETABLE` (
	`TT_NUM`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`TT_LEC_NUM`	INT	NOT NULL,
	`TT_TIME`	CHAR(2)	NULL
);

DROP TABLE IF EXISTS `SUBJECT`;

CREATE TABLE `SUBJECT` (
	`SBJ_NUM`	VARCHAR(6) PRIMARY KEY	NOT NULL,
	`SBJ_NAME`	VARCHAR(20) NOT	NULL,
	`SBJ_CREDIT`	INT NOT	NULL,
	`SBJ_TIME`	INT	NULL,
	`SBJ_MJ_CODE`	CHAR(3) NOT	NULL
);

DROP TABLE IF EXISTS `MAJOR`;

CREATE TABLE `MAJOR` (
	`MJ_NUM`	CHAR(3) PRIMARY KEY	NOT NULL,
	`MJ_NAME`	VARCHAR(20) NOT	NULL,
	`MJ_OFFICE`	VARCHAR(20)	NULL,
	`MJ_PRF_NUM`	CHAR(8)	NOT NULL
);

DROP TABLE IF EXISTS `LECTURE`;

CREATE TABLE `LECTURE` (
	`LEC_NUM`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`LEC_SBJ_NUM`	VARCHAR(6)	NOT NULL,
	`LEC_PRF_NUM`	CHAR(8)	NOT NULL,
	`LEC_YEAR`	CHAR(4) NOT	NULL,
	`LEC_SEMESTER`	ENUM("1","2","여름","겨울")	NULL,
	`LEC_AUDITORIUM`	VARCHAR(20)	NULL,
	`LEC_URL`	VARCHAR(255)	NULL,
	`LEC_CLASS`	INT	NULL,
	`LEC_MAX`	INT	NULL,
	`LEC_RAT_NUM`	INT	NOT NULL
);

ALTER TABLE `STUDENT` ADD CONSTRAINT `FK_MAJOR_TO_STUDENT_1` FOREIGN KEY (
	`STD_MJ_NUM`
)
REFERENCES `MAJOR` (
	`MJ_NUM`
);

ALTER TABLE `STUDENT` ADD CONSTRAINT `FK_STUDENT_DATA_TO_STUDENT_1` FOREIGN KEY (
	`STD_SD_NUM`
)
REFERENCES `STUDENT_DATA` (
	`SD_NUM`
);

ALTER TABLE `GRADE` ADD CONSTRAINT `FK_STUDENT_TO_GRADE_1` FOREIGN KEY (
	`GR_STD_NUM`
)
REFERENCES `STUDENT` (
	`STD_NUM`
);

ALTER TABLE `GRADE` ADD CONSTRAINT `FK_LECTURE_TO_GRADE_1` FOREIGN KEY (
	`GR_LEC_NUM`
)
REFERENCES `LECTURE` (
	`LEC_NUM`
);

ALTER TABLE `PROFESSOR` ADD CONSTRAINT `FK_MAJOR_TO_PROFESSOR_1` FOREIGN KEY (
	`PRF_MJ_NUM`
)
REFERENCES `MAJOR` (
	`MJ_NUM`
);

ALTER TABLE `TIMETABLE` ADD CONSTRAINT `FK_LECTURE_TO_TIMETABLE_1` FOREIGN KEY (
	`TT_LEC_NUM`
)
REFERENCES `LECTURE` (
	`LEC_NUM`
);

ALTER TABLE `MAJOR` ADD CONSTRAINT `FK_PROFESSOR_TO_MAJOR_1` FOREIGN KEY (
	`MJ_PRF_NUM`
)
REFERENCES `PROFESSOR` (
	`PRF_NUM`
);

ALTER TABLE `LECTURE` ADD CONSTRAINT `FK_SUBJECT_TO_LECTURE_1` FOREIGN KEY (
	`LEC_SBJ_NUM`
)
REFERENCES `SUBJECT` (
	`SBJ_NUM`
);

ALTER TABLE `LECTURE` ADD CONSTRAINT `FK_PROFESSOR_TO_LECTURE_1` FOREIGN KEY (
	`LEC_PRF_NUM`
)
REFERENCES `PROFESSOR` (
	`PRF_NUM`
);

ALTER TABLE `LECTURE` ADD CONSTRAINT `FK_RATIO_TO_LECTURE_1` FOREIGN KEY (
	`LEC_RAT_NUM`
)
REFERENCES `RATIO` (
	`RAT_NUM`
);

