DROP DATABASE IF EXISTS `UNIVERSITY`;

CREATE DATABASE `UNIVERSITY`;

USE `UNIVERSITY`;


DROP TABLE IF EXISTS `STUDENT_DATA`;

CREATE TABLE `STUDENT_DATA` (
	`SD_NUM`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`SD_NAME`	VARCHAR(20) NOT	NULL,
	`SD_PHONE`	VARCHAR(20) NOT	NULL,
	`SD_RESIDENT`	CHAR(14) UNIQUE NOT	NULL,
	`SD_YEAR`	INT NOT	NULL
);

DROP TABLE IF EXISTS `LECTURE_SCHEDULE`;

CREATE TABLE `LECTURE_SCHEDULE` (
	`LC_NUM`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`LC_LEC_NUM`	INT	NOT NULL,
	`LC_DAY`	CHAR(1) NOT	NULL,
	`LC_TIME`	VARCHAR(2) NOT	NULL,
	`LC_MINUTE`	CHAR(1) NOT	NULL
);

DROP TABLE IF EXISTS `LECTURE_STANDARD`;

CREATE TABLE `LECTURE_STANDARD` (
	`LS_NUM`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`LS_MID`	INT DEFAULT 35 NOT	NULL,
	`LS_FIN`	INT DEFAULT 45 NOT	NULL,
	`LS_HW`	INT DEFAULT 10 NOT	NULL,
	`LS_ATT`	INT DEFAULT 10 NOT	NULL,
	`LS_LEC_NUM`	INT	NOT NULL
);

DROP TABLE IF EXISTS `PROFESSOR`;

CREATE TABLE `PROFESSOR` (
	`PRF_NUM`	CHAR(8) PRIMARY KEY	NOT NULL,
	`PRF_DE_NUM`	CHAR(3)	NOT NULL,
	`PRF_NAME`	VARCHAR(20) NOT	NULL,
	`PRF_PHONE`	VARCHAR(20) NOT	NULL,
	`PRF_RESIDENT`	CHAR(14) UNIQUE NOT	NULL,
	`PRF_YEAR`	INT NOT	NULL
);

DROP TABLE IF EXISTS `SUBJECT_CATEGORY`;

CREATE TABLE `SUBJECT_CATEGORY` (
	`SC_CODE`	CHAR(3) PRIMARY KEY	NOT NULL
);

DROP TABLE IF EXISTS `COURSE`;

CREATE TABLE `COURSE` (
	`GR_NUM`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`GR_STD_NUM`	VARCHAR(10)	NOT NULL,
	`GR_LEC_NUM`	INT	NOT NULL,
	`GR_ATT`	INT DEFAULT 0 NOT	NULL,
	`GR_HOMEWORK`	INT DEFAULT 0 NOT	NULL,
	`GR_MIDDLE`	INT DEFAULT 0 NOT	NULL,
	`GR_FINAL`	INT DEFAULT 0 NOT	NULL,
	`GR_GRADE`	VARCHAR(4)	NULL
);

DROP TABLE IF EXISTS `LECTURE`;

CREATE TABLE `LECTURE` (
	`LEC_NUM`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`LEC_SBJ_NUM`	INT	NOT NULL,
	`LEC_PRF_NUM`	CHAR(8)	NOT NULL,
	`LEC_YEAR`	INT NOT	NULL,
	`LEC_SEMESTER`	ENUM("1","2","여름","겨울") NOT	NULL,
	`LEC_AUDITORIUM`	VARCHAR(255)	NULL,
	`LEC_PLAN`	LONGTEXT	NULL,
	`LEC_CLASS`	INT DEFAULT 1 NOT	NULL,
	`LEC_MAX`	INT NOT	NULL
);

DROP TABLE IF EXISTS `DEPARTMENT`;

CREATE TABLE `DEPARTMENT` (
	`DE_NUM`	CHAR(3) PRIMARY KEY	NOT NULL,
	`DE_NAME`	VARCHAR(50) NOT	NULL,
	`DE_OFFICE`	VARCHAR(20)	NULL,
	`DE_PRF_NUM`	CHAR(8)	NOT NULL
);

DROP TABLE IF EXISTS `STUDENT`;

CREATE TABLE `STUDENT` (
	`STD_NUM`	VARCHAR(10) PRIMARY KEY	NOT NULL,
	`STD_MJ_NUM`	CHAR(3)	NOT NULL,
	`STD_SD_NUM`	INT	NOT NULL,
	`STD_PRF_NUM`	CHAR(8)	NOT NULL
);

DROP TABLE IF EXISTS `STUDENT_APPLICATION`;

CREATE TABLE `STUDENT_APPLICATION` (
	`SA_NUM`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`SA_NAME`	VARCHAR(20) NOT	NULL,
	`SA_PHONE`	VARCHAR(20) NOT	NULL,
	`SA_RESIDENT`	CHAR(14) NOT	NULL,
	`SA_DE_NUM`	CHAR(3)	NOT NULL,
	`SA_YEAR`	INT NOT	NULL
);

DROP TABLE IF EXISTS `SUBJECT`;

CREATE TABLE `SUBJECT` (
	`SBJ_NUM`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`SBJ_NAME`	VARCHAR(20) NOT	NULL,
	`SBJ_CREDIT`	INT DEFAULT 0 NOT	NULL,
	`SBJ_TIME`	INT DEFAULT 0 NOT	NULL,
	`SBJ_CODE`	CHAR(6) UNIQUE NOT	NULL,
	`SBJ_SC_CODE`	CHAR(3)	NOT NULL
);

ALTER TABLE `LECTURE_SCHEDULE` ADD CONSTRAINT `FK_LECTURE_TO_LECTURE_SCHEDULE_1` FOREIGN KEY (
	`LC_LEC_NUM`
)
REFERENCES `LECTURE` (
	`LEC_NUM`
);

ALTER TABLE `LECTURE_STANDARD` ADD CONSTRAINT `FK_LECTURE_TO_LECTURE_STANDARD_1` FOREIGN KEY (
	`LS_LEC_NUM`
)
REFERENCES `LECTURE` (
	`LEC_NUM`
);

ALTER TABLE `PROFESSOR` ADD CONSTRAINT `FK_DEPARTMENT_TO_PROFESSOR_1` FOREIGN KEY (
	`PRF_DE_NUM`
)
REFERENCES `DEPARTMENT` (
	`DE_NUM`
);

ALTER TABLE `COURSE` ADD CONSTRAINT `FK_STUDENT_TO_COURSE_1` FOREIGN KEY (
	`GR_STD_NUM`
)
REFERENCES `STUDENT` (
	`STD_NUM`
);

ALTER TABLE `COURSE` ADD CONSTRAINT `FK_LECTURE_TO_COURSE_1` FOREIGN KEY (
	`GR_LEC_NUM`
)
REFERENCES `LECTURE` (
	`LEC_NUM`
);

ALTER TABLE `LECTURE` ADD CONSTRAINT `FK_SUBJECT_TO_LECTURE_1` FOREIGN KEY (
	`LEC_SBJ_NUM`
)
REFERENCES `SUBJECT` (
	`SBJ_NUM`
);

ALTER TABLE `LECTURE` ADD CONSTRAINT `FK_PROFESSOR_TO_LECTURE_1` FOREIGN KEY (
	`LEC_PRF_NUM`
)
REFERENCES `PROFESSOR` (
	`PRF_NUM`
);

ALTER TABLE `DEPARTMENT` ADD CONSTRAINT `FK_PROFESSOR_TO_DEPARTMENT_1` FOREIGN KEY (
	`DE_PRF_NUM`
)
REFERENCES `PROFESSOR` (
	`PRF_NUM`
);

ALTER TABLE `STUDENT` ADD CONSTRAINT `FK_DEPARTMENT_TO_STUDENT_1` FOREIGN KEY (
	`STD_MJ_NUM`
)
REFERENCES `DEPARTMENT` (
	`DE_NUM`
);

ALTER TABLE `STUDENT` ADD CONSTRAINT `FK_STUDENT_DATA_TO_STUDENT_1` FOREIGN KEY (
	`STD_SD_NUM`
)
REFERENCES `STUDENT_DATA` (
	`SD_NUM`
);

ALTER TABLE `STUDENT` ADD CONSTRAINT `FK_PROFESSOR_TO_STUDENT_1` FOREIGN KEY (
	`STD_PRF_NUM`
)
REFERENCES `PROFESSOR` (
	`PRF_NUM`
);

ALTER TABLE `STUDENT_APPLICATION` ADD CONSTRAINT `FK_DEPARTMENT_TO_STUDENT_APPLICATION_1` FOREIGN KEY (
	`SA_DE_NUM`
)
REFERENCES `DEPARTMENT` (
	`DE_NUM`
);

ALTER TABLE `SUBJECT` ADD CONSTRAINT `FK_SUBJECT_CATEGORY_TO_SUBJECT_1` FOREIGN KEY (
	`SBJ_SC_CODE`
)
REFERENCES `SUBJECT_CATEGORY` (
	`SC_CODE`
);

