CREATE TABLE `SCORE` (
	`SC_NUM`	INT	NOT NULL,
	`SC_SCORE`	INT	NULL,
	`SC_ST_KEY`	INT	NOT NULL,
	`SC_SJ_NUM`	INT	NOT NULL
);

CREATE TABLE `STUDENT NAME` (
	`ST_KEY`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`ST_GRADE`	INT	NULL,
	`ST_CLASS`	INT	NULL,
	`ST_NUM`	INT	NULL,
	`ST_NAME`	VARCHAR(20)	NULL
);

CREATE TABLE `SUBJECT` (
	`SJ_NUM`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`SJ_GRADE`	INT	NULL,
	`SJ_SEMESTER`	ENUM("1","2")	NULL,
	`SJ_NAME`	VARCHAR(10)	NULL
);

ALTER TABLE `SCORE` ADD CONSTRAINT `PK_SCORE` PRIMARY KEY (
	`SC_NUM`
);

ALTER TABLE `STUDENT NAME` ADD CONSTRAINT `PK_STUDENT NAME` PRIMARY KEY (
	`ST_KEY`
);

ALTER TABLE `SUBJECT` ADD CONSTRAINT `PK_SUBJECT` PRIMARY KEY (
	`SJ_NUM`
);
